"""Monthly analytics report generator.

Run via: python -m src.reports.monthly_report
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import structlog

from src.database import Database
from src.models import ApprovalStatus, SourceType
from src.config import settings

logger = structlog.get_logger(__name__)


def generate_monthly_report() -> str:
    """Generate a markdown monthly analytics report."""
    db = Database(settings.db_path)
    db.initialize()

    total = db.count_processed_ideas()
    approved = db.count_processed_ideas(ApprovalStatus.APPROVED)
    rejected = db.count_processed_ideas(ApprovalStatus.REJECTED)
    duplicates = db.count_processed_ideas(ApprovalStatus.DUPLICATE)

    approved_ideas = db.get_all_approved_ideas()

    # Source breakdown
    source_counts: dict[str, int] = {}
    for idea in approved_ideas:
        src = idea.source.value
        source_counts[src] = source_counts.get(src, 0) + 1

    # Category breakdown
    category_counts: dict[str, int] = {}
    for idea in approved_ideas:
        for cat in idea.categories:
            category_counts[cat] = category_counts.get(cat, 0) + 1
    top_categories = sorted(category_counts.items(), key=lambda x: -x[1])[:10]

    # Language breakdown
    language_counts: dict[str, int] = {}
    for idea in approved_ideas:
        if idea.language:
            lang = idea.language.lower()
            language_counts[lang] = language_counts.get(lang, 0) + 1
    top_languages = sorted(language_counts.items(), key=lambda x: -x[1])[:10]

    # Difficulty breakdown
    difficulty_counts: dict[str, int] = {}
    for idea in approved_ideas:
        diff = idea.difficulty.value
        difficulty_counts[diff] = difficulty_counts.get(diff, 0) + 1

    # AI statistics
    ai_rejection_reasons: dict[str, int] = {}
    for idea in approved_ideas:
        if idea.ai_reasoning:
            # Simple categorization of rejection reasons
            reason_lower = idea.ai_reasoning.lower()
            if "duplicate" in reason_lower:
                ai_rejection_reasons["duplicate"] = ai_rejection_reasons.get("duplicate", 0) + 1
            elif "spam" in reason_lower:
                ai_rejection_reasons["spam"] = ai_rejection_reasons.get("spam", 0) + 1
            elif "not a project" in reason_lower or "not an idea" in reason_lower:
                ai_rejection_reasons["not_a_project"] = ai_rejection_reasons.get("not_a_project", 0) + 1
            elif "low quality" in reason_lower:
                ai_rejection_reasons["low_quality"] = ai_rejection_reasons.get("low_quality", 0) + 1
            else:
                ai_rejection_reasons["other"] = ai_rejection_reasons.get("other", 0) + 1

    now = datetime.utcnow()
    approval_rate = (approved / total * 100) if total > 0 else 0

    report = f"""# Monthly Analytics Report

**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}

## Overview

| Metric | Value |
|--------|-------|
| Total Ideas Processed | {total} |
| Approved | {approved} |
| Rejected | {rejected} |
| Duplicates | {duplicates} |
| Approval Rate | {approval_rate:.1f}% |

## Source Performance

| Source | Ideas | Percentage |
|--------|-------|------------|
"""

    for src_name in ("github", "reddit", "hackernews"):
        count = source_counts.get(src_name, 0)
        pct = (count / approved * 100) if approved > 0 else 0
        report += f"| {src_name.title()} | {count} | {pct:.1f}% |\n"

    report += f"""
## Top Categories

| Category | Count |
|----------|-------|
"""
    for cat, count in top_categories:
        report += f"| {cat} | {count} |\n"

    report += f"""
## Top Technologies

| Technology | Count |
|------------|-------|
"""
    for lang, count in top_languages:
        report += f"| {lang.title()} | {count} |\n"

    report += f"""
## Difficulty Distribution

| Level | Count |
|-------|-------|
"""
    for diff in ("Beginner", "Intermediate", "Advanced"):
        count = difficulty_counts.get(diff, 0)
        report += f"| {diff} | {count} |\n"

    report += f"""
## AI Rejection Reasons

| Reason | Count |
|--------|-------|
"""
    for reason, count in sorted(ai_rejection_reasons.items(), key=lambda x: -x[1]):
        report += f"| {reason.replace('_', ' ').title()} | {count} |\n"

    report += "\n---\n*Report generated by Open Source Radar*\n"

    # Save report
    reports_dir = settings.reports_path
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"monthly_report_{now.strftime('%Y_%m')}.md"
    report_path.write_text(report)
    logger.info("monthly_report_generated", path=str(report_path))

    return report


if __name__ == "__main__":
    generate_monthly_report()
